### ISSUE TITLE
Can't change region or access aws

### ISSUE THREAD

**Issue by krdzo** [cniles/axe#7]
Hi, I tried to use this package but when I run `axe-s3-list-buckets` I always get these two errors. The first is this:
```
Error thrown:

(error http 403)

Error data:

(Error nil (Code nil InvalidAccessKeyId) (Message nil The AWS Access Key Id you provided does not exist in our records.) (AWSAccessKeyId nil <example>) (RequestId nil <example>) (HostId nil <example>))

```

and when I try to change `axe-region` to my region `eu-west-1` then I get this error:

```
Error thrown:

(error http 400)

Error data:

(Error nil (Code nil AuthorizationHeaderMalformed) (Message nil The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1') (Region nil us-east-1) (RequestId nil <example>) (HostId nil <example>
```

(I put the `<example>` to redact my keys).
Don't know what to do with this is it my i.e. user error, or it is a bug.

P.S. in the README you put the varables `aws-access-key-id` and `aws-secret-access-key` that that don't exist. As far as I understend you intended to put `axe-access-key-id` and `axe-secret-access-key`.

**Comment by cniles** [comment]
Definitely a bug, thanks for reporting.  I'll review how endpoints are used for s3...seems `s3.amazonaws.com` resolves to `us-east-1` region.
